"""Florida regions, cities and military communities."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
EXIT = ("For the 2026 plan year AvMed left the Florida Medicare market and UnitedHealthcare reduced plans in many counties. "
        "A plan leaving you gives you a Special Enrollment Period and, in most cases, a guaranteed-issue right to a Medigap policy without health questions.")
NET = "Each system contracts with some Medicare Advantage plans and not others, and the lists change every October. With Original Medicare and a Medigap policy there is no network to check. We confirm your doctors before you enroll."

REGIONS = [
    dict(slug="south-florida", name="South Florida", short="South Florida", scene="miami",
         eyebrow="Medicare by region · Miami-Dade, Broward &amp; Palm Beach",
         h1="Medicare help across South Florida",
         sub="Miami, Fort Lauderdale, Boca Raton and West Palm Beach &mdash; the most Advantage-heavy Medicare market in America, the deepest menu, and the counties UnitedHealthcare and AvMed pulled back from for 2026.",
         counties="Miami-Dade, Broward, Palm Beach, Monroe",
         cities=["miami", "fort-lauderdale", "west-palm-beach", "boca-raton"],
         systems=["Baptist Health South Florida", "Jackson Health System", "UHealth (University of Miami)", "Mount Sinai Medical Center", "Memorial Healthcare System", "Broward Health", "Cleveland Clinic Florida (Weston)", "HCA Florida"],
         note="<p><strong>What changed for 2026:</strong> AvMed, a South Florida institution, left the Medicare market entirely, and UnitedHealthcare cut plans in Miami-Dade, Broward and Palm Beach. Many South Floridians shopped for the first time in years. The menu is still the deepest in the state &mdash; Florida Blue, Humana, CarePlus, Aetna, HealthSpring, Devoted, Simply, HealthSun and others &mdash; and every plan rides on a different set of the region&rsquo;s many hospital systems.</p>",
         intro=["South Florida has more people on Medicare Advantage than most entire states, and its care is spread across a dozen systems that each contract on their own terms: Baptist Health, Jackson, UHealth and Mount Sinai in Miami-Dade; Memorial, Broward Health, Cleveland Clinic and Holy Cross in Broward; Baptist&rsquo;s Boca Raton Regional and the Tenet and HCA hospitals in Palm Beach. A $0-premium plan that includes your cardiologist at Baptist may exclude your oncologist at UHealth.",
                "Monroe County and the Keys are their own market with a single hospital system and thin menus, and a lot of South Floridians split the year with the Northeast, which is where a Medigap policy&rsquo;s any-provider access earns its premium."],
         faqs=[("Which Medicare plans are available in Miami-Dade, Broward and Palm Beach?", "The deepest Medicare Advantage menu in Florida, including many Dual Special Needs Plans, plus every Medigap carrier in the state and the full Part D lineup. Availability is set by county and changes each plan year; for 2026 AvMed left and UnitedHealthcare reduced its plans here."),
               ("Does Cleveland Clinic Florida or UHealth take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="tampa-bay", name="Tampa Bay", short="Tampa Bay", scene="macdill",
         eyebrow="Medicare by region · Tampa, St. Petersburg, Clearwater &amp; Sarasota",
         h1="Medicare help across Tampa Bay",
         sub="Hillsborough, Pinellas, Pasco, Manatee and Sarasota counties &mdash; Tampa General, BayCare, Moffitt and Sarasota Memorial, MacDill Air Force Base, and one of the largest retiree populations on the Gulf.",
         counties="Hillsborough, Pinellas, Pasco, Hernando, Manatee, Sarasota",
         cities=["tampa", "st-petersburg", "clearwater", "sarasota", "macdill-afb"],
         systems=["Tampa General Hospital", "BayCare (St. Joseph&rsquo;s, Morton Plant, Mease)", "Moffitt Cancer Center", "AdventHealth Tampa &amp; Wesley Chapel", "HCA Florida (Brandon, Largo, Trinity)", "Sarasota Memorial", "Manatee Memorial", "James A. Haley &amp; Bay Pines VA"],
         note="<p><strong>What changed for 2026:</strong> UnitedHealthcare reduced plans in Hillsborough and Pinellas, and several carriers trimmed dental, vision and OTC extras. Tampa Bay&rsquo;s menu remains deep, split mainly between plans built on BayCare and plans built on Tampa General and AdventHealth; Moffitt contracts selectively.</p>",
         intro=["Tampa Bay is Florida&rsquo;s second-largest Medicare market and its most system-divided: BayCare dominates Pinellas and much of Pasco, Tampa General and AdventHealth anchor Hillsborough, HCA fills in around them, and Sarasota Memorial stands alone to the south. Moffitt Cancer Center, like MD Anderson in Texas, accepts Original Medicare and contracts with only some Advantage plans.",
                "MacDill Air Force Base gives the region a large TRICARE For Life population, and the Haley and Bay Pines VA medical centers are among the busiest in the country; both change what &ldquo;best plan&rdquo; means."],
         faqs=[("Which Medicare plans are available in Tampa Bay?", "Hillsborough, Pinellas and Pasco counties typically offer a deep Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. For 2026 UnitedHealthcare reduced plans in Hillsborough and Pinellas."),
               ("Does Moffitt take Medicare Advantage?", "Moffitt accepts Original Medicare and therefore any Medigap policy. It contracts with some Medicare Advantage plans and not others, and the list changes yearly. If Moffitt is your care or a possibility, we confirm the plan&rsquo;s status in writing before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="central-florida", name="Central Florida &amp; The Villages", short="Central Florida", scene="citrus",
         eyebrow="Medicare by region · Orlando, The Villages, Lakeland &amp; Ocala",
         h1="Medicare help across Central Florida and The Villages",
         sub="Orange, Seminole, Osceola, Lake, Sumter, Marion and Polk counties &mdash; AdventHealth and Orlando Health, the largest retirement community in the country, and a menu that changes every fall.",
         counties="Orange, Seminole, Osceola, Lake, Sumter, Marion, Polk, Volusia (west)",
         cities=["orlando", "the-villages", "ocala", "lakeland"],
         systems=["AdventHealth (Orlando, Ocala, Lake Placid)", "Orlando Health", "UF Health The Villages &amp; Leesburg", "HCA Florida (Osceola, Ocala, Poinciana)", "Lakeland Regional Health", "Orlando VA Medical Center"],
         note="<p><strong>What to watch:</strong> The Villages and the Lake–Sumter–Marion corridor have some of the highest Medicare Advantage enrollment anywhere, and carriers compete hard for it, so the lineup shifts every October. Orlando&rsquo;s care is split between AdventHealth and Orlando Health, which contract differently.</p>",
         intro=["Central Florida is where the state&rsquo;s Medicare growth is: The Villages alone adds thousands of beneficiaries a year, and Orange, Seminole and Polk counties are not far behind. Orlando&rsquo;s care runs through AdventHealth and Orlando Health; The Villages through UF Health The Villages Hospital and the community&rsquo;s primary-care network; Ocala through AdventHealth and HCA. Which of those a plan includes is the first thing we check.",
                "A lot of Central Floridians arrived recently from the Northeast or Midwest, and their plan from home may not have come with them; our <a href=\"/new-to-florida\">new-to-Florida guide</a> covers the move."],
         faqs=[("Which Medicare plans are available in Orlando and The Villages?", "Orange and Sumter counties typically offer a deep Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Availability changes each plan year and The Villages&rsquo; lineup shifts every October."),
               ("Are AdventHealth and Orlando Health in the same plans?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="southwest-florida", name="Southwest Florida", short="Southwest Florida", scene="beach",
         eyebrow="Medicare by region · Fort Myers, Naples, Cape Coral &amp; Punta Gorda",
         h1="Medicare help across Southwest Florida",
         sub="Lee, Collier and Charlotte counties &mdash; Lee Health and NCH, a retiree-heavy coast still rebuilding from Ian, and counties UnitedHealthcare pulled back from for 2026.",
         counties="Lee, Collier, Charlotte, Hendry, Glades",
         cities=["fort-myers", "cape-coral", "naples"],
         systems=["Lee Health (Lee Memorial, Gulf Coast, Cape Coral, HealthPark)", "NCH Healthcare System (Naples)", "Physicians Regional (Naples)", "ShorePoint Health (Port Charlotte, Punta Gorda)", "Lee County VA Healthcare Center"],
         note="<p><strong>What changed for 2026:</strong> UnitedHealthcare reduced plans in Lee and Collier counties. Lee Health, the public system that runs nearly every hospital in Lee County, contracts with some plans and not others, and NCH in Naples does the same, so the system question is sharp here.</p>",
         intro=["Southwest Florida is retiree country with a concentrated care map: Lee Health runs almost every hospital in Lee County, NCH and Physicians Regional split Naples, and ShorePoint serves Charlotte. Because there are few alternatives, a plan that excludes your system is a real problem, and the 2026 pullbacks narrowed the menu.",
                "Hurricane Ian also taught this coast what a FEMA disaster declaration does to Medicare deadlines; our <a href=\"/hurricanes\">hurricanes page</a> covers the Special Enrollment Period."],
         faqs=[("Which Medicare plans are available in Fort Myers and Naples?", "Lee and Collier counties typically offer a moderate-to-deep Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. For 2026 UnitedHealthcare reduced plans here."),
               ("Is Lee Health in my plan&rsquo;s network?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="northeast-florida", name="Northeast Florida &amp; the First Coast", short="Northeast Florida", scene="lighthouse",
         eyebrow="Medicare by region · Jacksonville, St. Augustine &amp; the beaches",
         h1="Medicare help across Northeast Florida and the First Coast",
         sub="Duval, St. Johns, Clay and Nassau counties &mdash; Mayo Clinic, Baptist Health, UF Health Jacksonville, two naval bases, and the fastest-growing county in the state.",
         counties="Duval, St. Johns, Clay, Nassau, Baker, Putnam, Flagler",
         cities=["jacksonville", "jacksonville-navy"],
         systems=["Mayo Clinic Jacksonville", "Baptist Health Jacksonville", "UF Health Jacksonville", "Ascension St. Vincent&rsquo;s", "HCA Florida Memorial &amp; Orange Park", "Flagler Health+ (St. Augustine)", "Naval Hospital Jacksonville (TRICARE)"],
         note="<p><strong>What to watch:</strong> Mayo Clinic Jacksonville accepts Original Medicare and contracts with only some Advantage plans, which is why so many First Coast retirees keep a Medigap policy. NAS Jacksonville and Naval Station Mayport give the region a large TRICARE For Life population.</p>",
         intro=["Northeast Florida&rsquo;s Medicare question often starts with Mayo. The Jacksonville campus takes Original Medicare, and therefore any Medigap policy, but contracts selectively with Advantage plans; Baptist, UF Health and Ascension St. Vincent&rsquo;s each contract separately again. St. Johns County, the fastest-growing in Florida, has a deep menu; Putnam and Baker have thin ones.",
                "The naval bases add a TRICARE For Life layer that changes the calculation entirely; see our <a href=\"/jacksonville-navy\">Jacksonville Navy page</a>."],
         faqs=[("Which Medicare plans are available in Jacksonville?", "Duval and St. Johns counties typically offer a deep Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Availability changes each plan year."),
               ("Does Mayo Clinic Jacksonville take Medicare Advantage?", "Mayo accepts Original Medicare and therefore any Medigap policy. It contracts with some Medicare Advantage plans and not others, and the list changes yearly. If Mayo is your care, we confirm the plan&rsquo;s status in writing before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="panhandle", name="The Panhandle &amp; Emerald Coast", short="the Panhandle", scene="beach",
         eyebrow="Medicare by region · Pensacola, Destin, Panama City &amp; Tallahassee",
         h1="Medicare help across the Panhandle and Emerald Coast",
         sub="Escambia, Okaloosa, Bay and Leon counties and the rural counties between &mdash; NAS Pensacola and Eglin, Baptist and Ascension Sacred Heart, TMH in Tallahassee, and thinner menus than the peninsula.",
         counties="Escambia, Santa Rosa, Okaloosa, Walton, Bay, Leon, Gadsden, Jackson, Gulf, Franklin, Wakulla",
         cities=["pensacola", "tallahassee", "pensacola-eglin"],
         systems=["Baptist Health Care (Pensacola)", "Ascension Sacred Heart (Pensacola, Destin, Panama City)", "HCA Florida West &amp; Fort Walton-Destin", "Tallahassee Memorial HealthCare", "HCA Florida Capital (Tallahassee)", "Naval Hospital Pensacola &amp; Eglin AFB Hospital (TRICARE)"],
         note="<p><strong>What to watch:</strong> The Panhandle&rsquo;s menus are shorter than the peninsula&rsquo;s and shrink fast outside Escambia, Okaloosa, Bay and Leon. The military-retiree population around Pensacola and Eglin is among the largest in the country, and many residents cross into Alabama for care, which a Medigap policy covers automatically.</p>",
         intro=["The Panhandle is a different Medicare market from the peninsula: fewer carriers, thinner networks, and a lot of retirees who see doctors in Mobile or Dothan. Pensacola&rsquo;s care is split between Baptist and Ascension Sacred Heart; Tallahassee&rsquo;s between TMH and HCA Capital; the rural counties in between lean on a single hospital.",
                "NAS Pensacola, NAS Whiting Field, Eglin, Hurlburt and Tyndall give the region an enormous TRICARE For Life population; see our <a href=\"/pensacola-eglin\">Pensacola and Eglin page</a>."],
         faqs=[("Which Medicare plans are available in Pensacola or Tallahassee?", "Escambia and Leon counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Rural Panhandle counties have fewer Advantage plans."),
               ("Can I see a doctor in Alabama with a Florida plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the Alabama provider is in-network, which we confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="treasure-space-coast", name="Treasure Coast &amp; Space Coast", short="the Treasure and Space Coasts", scene="spacecoast",
         eyebrow="Medicare by region · Melbourne, Vero Beach, Port St. Lucie &amp; Daytona",
         h1="Medicare help across the Treasure Coast and Space Coast",
         sub="Brevard, Indian River, St. Lucie, Martin and Volusia counties &mdash; Health First, Cleveland Clinic Martin and Tradition, Halifax and AdventHealth Daytona, Patrick Space Force Base, and a fast-growing retiree corridor.",
         counties="Brevard, Indian River, St. Lucie, Martin, Volusia, Okeechobee",
         cities=["melbourne", "port-st-lucie", "daytona-beach"],
         systems=["Health First (Melbourne, Viera, Cape Canaveral)", "Cleveland Clinic Martin Health &amp; Tradition", "HCA Florida St. Lucie &amp; Lawnwood", "Cleveland Clinic Indian River", "Halifax Health (Daytona)", "AdventHealth Daytona Beach &amp; New Smyrna", "Viera VA Clinic"],
         note="<p><strong>What to watch:</strong> Health First runs both the dominant hospital system and its own Advantage plans in Brevard, so system and plan are often the same company. Cleveland Clinic&rsquo;s Treasure Coast hospitals contract selectively; Volusia is split between Halifax and AdventHealth.</p>",
         intro=["The Atlantic coast from Daytona to Stuart is a string of retiree communities, each with its own system: Halifax and AdventHealth in Volusia, Health First in Brevard, Cleveland Clinic in Indian River and Martin, HCA and Cleveland Clinic Tradition in St. Lucie. Port St. Lucie is among the fastest-growing cities in the country, and its lineup changes every October.",
                "Patrick Space Force Base and the Cape add a TRICARE For Life population to Brevard, and the Viera VA clinic serves veterans up and down the coast."],
         faqs=[("Which Medicare plans are available on the Treasure Coast and Space Coast?", "Brevard, St. Lucie and Volusia counties typically offer a deep Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Availability changes each plan year."),
               ("Is Cleveland Clinic Martin or Tradition in my plan&rsquo;s network?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="north-central-florida", name="North Central Florida", short="North Central Florida", scene="liveoaks",
         eyebrow="Medicare by region · Gainesville, Lake City &amp; the Nature Coast",
         h1="Medicare help across North Central Florida",
         sub="Alachua, Columbia, Citrus and Levy counties and the rural counties between &mdash; UF Health Shands, the Gainesville and Lake City VA, and thin menus outside the college town.",
         counties="Alachua, Columbia, Citrus, Levy, Marion (north), Suwannee, Bradford, Gilchrist, Dixie, Taylor",
         cities=["gainesville"],
         systems=["UF Health Shands (Gainesville)", "HCA Florida North Florida (Gainesville)", "HCA Florida Lake City", "HCA Florida Citrus", "Malcom Randall VA (Gainesville) &amp; Lake City VA"],
         note="<p><strong>What to watch:</strong> UF Health Shands is the region&rsquo;s academic center and contracts selectively with Advantage plans; outside Alachua County, menus are short and drives are long, which is where a Medigap policy earns its premium. The North Florida/South Georgia VA system is one of the largest in the country.</p>",
         intro=["North Central Florida is rural Florida with a university hospital in the middle. UF Health Shands handles the region&rsquo;s specialty care and takes Original Medicare with selective Advantage contracts; HCA fills in Gainesville, Lake City and Citrus County; the counties between lean on a single hospital or none. Advantage menus thin out fast past the Alachua line.",
                "The Nature Coast and Citrus County are quiet retirement destinations with a Medicare question that usually starts with whether a plan covers Ocala or Gainesville specialists."],
         faqs=[("Which Medicare plans are available in Gainesville?", "Alachua County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Surrounding rural counties have fewer Advantage plans."),
               ("Does UF Health Shands take Medicare Advantage?", "Shands accepts Original Medicare and therefore any Medigap policy, and contracts with some Medicare Advantage plans and not others. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)
def std(nm, county_menu):
    return [(f"Which Medicare plans are available in {nm}?", county_menu), (f"Will my {nm} doctors take a Medicare Advantage plan?", NET), ("How much does your help cost?", COST)]
DEEP = "typically offers a deep Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Availability is set by county and changes each plan year."
MOD = "typically offers a moderate Medicare Advantage menu, every Medigap carrier in Florida, and the full Part D lineup. Availability is set by county and changes each plan year."

CITIES = [
    city("jacksonville", "Jacksonville", "Duval County", "northeast-florida", "lighthouse",
         "Jacksonville&rsquo;s Medicare question often starts with Mayo Clinic, which takes Original Medicare and contracts selectively with Advantage plans. Baptist, UF Health and Ascension St. Vincent&rsquo;s each contract on their own terms.",
         ["Duval County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Mayo Clinic Jacksonville, Baptist Health, UF Health Jacksonville and Ascension St. Vincent&rsquo;s each sign their own Advantage contracts, and a plan that includes Baptist may exclude Mayo. NAS Jacksonville and Mayport add a large TRICARE For Life population.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy so the trade-off is plain."],
         ["Mayo Clinic Jacksonville", "Baptist Health Jacksonville", "UF Health Jacksonville", "Ascension St. Vincent&rsquo;s", "HCA Florida Memorial", "Naval Hospital Jacksonville (TRICARE)"],
         "Riverside, San Marco, Mandarin, Southside, Arlington, the Beaches, Orange Park, Fleming Island, Ponte Vedra, Fernandina",
         [("Which Medicare plans are available in Jacksonville?", "Duval County " + DEEP), ("Does Mayo Clinic Jacksonville take my Advantage plan?", "Mayo accepts Original Medicare and any Medigap policy, and contracts with some Advantage plans and not others, changing yearly. We confirm the plan&rsquo;s Mayo status in writing before you enroll."), ("How much does your help cost?", COST)],
         ["jacksonville-navy", "gainesville", "daytona-beach"]),
    city("miami", "Miami", "Miami-Dade County", "south-florida", "miami",
         "Miami-Dade has the deepest Advantage menu in Florida, the most Dual Special Needs Plans, and a care map split among Baptist Health, Jackson, UHealth and Mount Sinai &mdash; and it lost AvMed and part of UnitedHealthcare&rsquo;s lineup for 2026.",
         ["Miami-Dade offers dozens of Advantage plans, many D-SNPs, every Medigap carrier in Florida and the full Part D lineup. Baptist Health South Florida, Jackson Health, UHealth and Mount Sinai each contract separately, and AvMed&rsquo;s exit for 2026 sent tens of thousands of Miamians shopping.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and check whether a Medicare Savings Program or D-SNP applies."],
         ["Baptist Health South Florida", "Jackson Health System", "UHealth / Sylvester Cancer Center", "Mount Sinai Medical Center", "HCA Florida Kendall &amp; Aventura", "Miami VA Healthcare System"],
         "Coral Gables, Kendall, Hialeah, Miami Beach, Aventura, Doral, Homestead, Cutler Bay, Little Havana, Westchester",
         [("Which Medicare plans are available in Miami?", "Miami-Dade " + DEEP + " For 2026 AvMed left and UnitedHealthcare reduced its plans here."), ("Will my Baptist or UHealth doctors take a Medicare Advantage plan?", NET), ("How much does your help cost?", COST)],
         ["fort-lauderdale", "boca-raton"]),
    city("tampa", "Tampa", "Hillsborough County", "tampa-bay", "macdill",
         "Tampa&rsquo;s care runs through Tampa General, AdventHealth, BayCare&rsquo;s St. Joseph&rsquo;s and Moffitt, each contracting on its own terms, with MacDill Air Force Base and the Haley VA on top.",
         ["Hillsborough County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Tampa General, AdventHealth Tampa, BayCare St. Joseph&rsquo;s and HCA Brandon each contract separately, and Moffitt contracts selectively; UnitedHealthcare reduced its plans here for 2026.",
          "MacDill retirees with TRICARE For Life and veterans using the Haley VA have their own calculation; see our MacDill page."],
         ["Tampa General Hospital", "AdventHealth Tampa", "BayCare St. Joseph&rsquo;s", "Moffitt Cancer Center", "HCA Florida Brandon", "James A. Haley VA"],
         "South Tampa, Westchase, Carrollwood, New Tampa, Brandon, Riverview, Wesley Chapel, Lutz, Plant City, Temple Terrace",
         [("Which Medicare plans are available in Tampa?", "Hillsborough County " + DEEP + " For 2026 UnitedHealthcare reduced its plans here."), ("Does Moffitt take Medicare Advantage?", "Moffitt accepts Original Medicare and any Medigap policy, and contracts with some Advantage plans and not others. We confirm before you enroll."), ("How much does your help cost?", COST)],
         ["macdill-afb", "st-petersburg", "lakeland"]),
    city("orlando", "Orlando", "Orange County", "central-florida", "citrus",
         "Orlando is AdventHealth and Orlando Health territory, with a deep plan menu, the Orlando VA, and a steady stream of new residents whose plans from home did not come with them.",
         ["Orange County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. AdventHealth and Orlando Health contract with different carriers, so which system your doctors belong to decides the shortlist.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["AdventHealth Orlando", "Orlando Health / Orlando Regional Medical Center", "HCA Florida Osceola", "Orlando VA Medical Center (Lake Nona)"],
         "Winter Park, Dr. Phillips, Lake Nona, Apopka, Winter Garden, Ocoee, Altamonte Springs, Sanford, Kissimmee, Oviedo",
         std("Orlando", "Orange County " + DEEP), ["the-villages", "lakeland", "melbourne"]),
    city("st-petersburg", "St. Petersburg", "Pinellas County", "tampa-bay", "beach",
         "Pinellas is BayCare country &mdash; Morton Plant, Mease, St. Anthony&rsquo;s &mdash; with HCA hospitals and Bay Pines VA alongside, and a county UnitedHealthcare pulled plans from for 2026.",
         ["Pinellas County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. BayCare dominates local care and contracts selectively; HCA&rsquo;s Largo and Northside hospitals sit in different networks; Bay Pines is one of the busiest VA centers in the country.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["BayCare St. Anthony&rsquo;s &amp; Morton Plant", "HCA Florida Largo &amp; Northside", "Orlando Health Bayfront", "Bay Pines VA Healthcare System"],
         "St. Petersburg, Gulfport, Pinellas Park, Seminole, Largo, Treasure Island, St. Pete Beach, Madeira Beach",
         [("Which Medicare plans are available in St. Petersburg?", "Pinellas County " + DEEP + " For 2026 UnitedHealthcare reduced its plans here."), ("Is BayCare in my plan&rsquo;s network?", NET), ("How much does your help cost?", COST)],
         ["clearwater", "tampa", "sarasota"]),
    city("fort-lauderdale", "Fort Lauderdale", "Broward County", "south-florida", "miami",
         "Broward has a deep menu and four big systems &mdash; Memorial, Broward Health, Cleveland Clinic Florida and Holy Cross &mdash; and lost AvMed and some UnitedHealthcare plans for 2026.",
         ["Broward County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Memorial Healthcare, Broward Health, Cleveland Clinic Florida in Weston and Holy Cross each contract separately; AvMed&rsquo;s exit and UnitedHealthcare&rsquo;s cuts sent many Broward residents shopping for 2026.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Memorial Healthcare System", "Broward Health", "Cleveland Clinic Florida (Weston)", "Holy Cross Health", "HCA Florida Westside &amp; Northwest"],
         "Fort Lauderdale, Hollywood, Pembroke Pines, Coral Springs, Plantation, Weston, Pompano Beach, Deerfield Beach, Davie, Sunrise",
         [("Which Medicare plans are available in Fort Lauderdale?", "Broward County " + DEEP + " For 2026 AvMed left and UnitedHealthcare reduced its plans here."), ("Does Cleveland Clinic Florida take my Advantage plan?", NET), ("How much does your help cost?", COST)],
         ["miami", "boca-raton", "west-palm-beach"]),
    city("west-palm-beach", "West Palm Beach", "Palm Beach County", "south-florida", "keys",
         "Palm Beach County retirees split between Jupiter Medical, the Tenet and HCA hospitals, and Baptist&rsquo;s Boca Raton Regional, with a deep menu that lost some UnitedHealthcare plans for 2026.",
         ["Palm Beach County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Jupiter Medical Center, HCA Florida JFK and Palms West, Tenet&rsquo;s St. Mary&rsquo;s and Good Samaritan, and Baptist&rsquo;s Boca Raton Regional each contract separately, and the West Palm Beach VA serves veterans from Vero to Boca.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Jupiter Medical Center", "HCA Florida JFK &amp; Palms West", "St. Mary&rsquo;s &amp; Good Samaritan (Tenet)", "Baptist Health Boca Raton Regional", "West Palm Beach VA Medical Center"],
         "West Palm Beach, Palm Beach Gardens, Jupiter, Wellington, Royal Palm Beach, Lake Worth, Boynton Beach, Delray Beach",
         [("Which Medicare plans are available in West Palm Beach?", "Palm Beach County " + DEEP + " For 2026 UnitedHealthcare reduced its plans here."), ("Will my Jupiter Medical doctors take a Medicare Advantage plan?", NET), ("How much does your help cost?", COST)],
         ["boca-raton", "port-st-lucie", "fort-lauderdale"]),
    city("boca-raton", "Boca Raton", "Palm Beach County", "south-florida", "beach",
         "Boca Raton, Delray Beach and Deerfield have Baptist&rsquo;s Boca Raton Regional and Tenet&rsquo;s Delray Medical close by, a deep menu, and a large seasonal population from the Northeast.",
         ["South Palm Beach County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Boca Raton Regional (Baptist Health) and Delray Medical (Tenet) contract with different carriers, and many Boca households split the year with New York or New Jersey, which is where a Medigap policy&rsquo;s any-provider access matters.",
          "We compare what is sold at your ZIP code with your calendar in view."],
         ["Baptist Health Boca Raton Regional", "Delray Medical Center (Tenet)", "West Boca Medical Center", "Bethesda Hospital (Baptist)"],
         "Boca Raton, Delray Beach, Deerfield Beach, Highland Beach, Boynton Beach, Parkland",
         [("Which Medicare plans are available in Boca Raton?", "Palm Beach County " + DEEP), ("I split the year between Boca and New York. Which plan works?", "A Medigap policy with Original Medicare works in both places. County-based Advantage and Part D plans are tied to your permanent residence, and most Advantage HMOs cover only emergencies out of area. See our new-to-Florida guide."), ("How much does your help cost?", COST)],
         ["west-palm-beach", "fort-lauderdale"]),
    city("sarasota", "Sarasota", "Sarasota County", "tampa-bay", "beach",
         "Sarasota and Venice have one of the oldest populations of any U.S. metro, Sarasota Memorial at the center, and a menu built around whether a plan includes it.",
         ["Sarasota County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Sarasota Memorial, the public system, contracts selectively; HCA&rsquo;s Doctors Hospital and Englewood sit in different networks; Lakewood Ranch Medical Center serves the Manatee line.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Sarasota Memorial Health Care System", "HCA Florida Sarasota Doctors &amp; Englewood", "Lakewood Ranch Medical Center", "Venice Regional (ShorePoint)"],
         "Sarasota, Venice, North Port, Lakewood Ranch, Bradenton, Siesta Key, Longboat Key, Osprey, Nokomis",
         [("Which Medicare plans are available in Sarasota?", "Sarasota County " + DEEP), ("Is Sarasota Memorial in my plan&rsquo;s network?", NET), ("How much does your help cost?", COST)],
         ["st-petersburg", "fort-myers"]),
    city("fort-myers", "Fort Myers", "Lee County", "southwest-florida", "beach",
         "Lee Health runs nearly every hospital in Lee County, which makes the network question simple and unforgiving; UnitedHealthcare reduced plans here for 2026.",
         ["Lee County offers a moderate-to-deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Lee Health contracts with some plans and not others, and because it runs almost every hospital, a plan that excludes it is a real problem. The Lee County VA Healthcare Center serves veterans across the region.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Lee Health (Lee Memorial, Gulf Coast, HealthPark)", "Lee County VA Healthcare Center", "Physicians Regional (Naples)"],
         "Fort Myers, Estero, Bonita Springs, Lehigh Acres, Fort Myers Beach, Sanibel, North Fort Myers",
         [("Which Medicare plans are available in Fort Myers?", "Lee County " + MOD + " For 2026 UnitedHealthcare reduced its plans here."), ("Is Lee Health in my plan&rsquo;s network?", NET), ("How much does your help cost?", COST)],
         ["cape-coral", "naples", "sarasota"]),
    city("cape-coral", "Cape Coral", "Lee County", "southwest-florida", "keys",
         "Cape Coral is the largest city between Tampa and Miami and one of the fastest-growing retiree cities anywhere, with Lee Health Cape Coral Hospital at its center.",
         ["Lee County offers a moderate-to-deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Lee Health Cape Coral Hospital and the Lee Health system contract selectively, and the 2026 pullbacks narrowed the menu.",
          "Many Cape Coral residents arrived recently from the Midwest; our new-to-Florida guide covers the move."],
         ["Lee Health Cape Coral Hospital", "Lee Health (Fort Myers)", "Lee County VA Healthcare Center"],
         "Cape Coral, Matlacha, Pine Island, North Fort Myers, Burnt Store",
         std("Cape Coral", "Lee County " + MOD), ["fort-myers", "naples"]),
    city("naples", "Naples", "Collier County", "southwest-florida", "beach",
         "Naples and Marco Island have NCH and Physicians Regional, a wealthy retiree population with high IRMAA exposure, and a county UnitedHealthcare pulled plans from for 2026.",
         ["Collier County offers a moderate Advantage menu, every Medigap carrier in Florida and the full Part D lineup. NCH Healthcare System and Physicians Regional contract with different carriers, and many Naples households split the year with the Northeast or Midwest, which favors a Medigap policy.",
          "We compare what is sold at your ZIP code with your calendar and your tax return in view."],
         ["NCH Healthcare System", "Physicians Regional Healthcare System", "Lee Health (Fort Myers)"],
         "Naples, Marco Island, Bonita Springs, Golden Gate, Ave Maria, Immokalee, Everglades City",
         [("Which Medicare plans are available in Naples?", "Collier County " + MOD + " For 2026 UnitedHealthcare reduced its plans here."), ("Is NCH in my plan&rsquo;s network?", NET), ("How much does your help cost?", COST)],
         ["fort-myers", "cape-coral"]),
    city("the-villages", "The Villages", "Sumter County", "central-florida", "citrus",
         "The Villages is the largest retirement community in the country, and carriers compete for it every October. UF Health The Villages Hospital and the community&rsquo;s primary-care network are the network question.",
         ["Sumter, Lake and Marion counties offer a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. UF Health The Villages Hospital and UF Health Leesburg anchor hospital care; the community&rsquo;s primary-care clinics contract with some plans and not others, and the lineup shifts every year.",
          "Almost everyone here arrived from somewhere else; our new-to-Florida guide covers what the move did to your plan and your Medigap rights."],
         ["UF Health The Villages Hospital", "UF Health Leesburg Hospital", "AdventHealth Ocala", "Villages-area primary-care clinics"],
         "The Villages, Lady Lake, Wildwood, Fruitland Park, Leesburg, Summerfield, Oxford",
         [("Which Medicare plans are available in The Villages?", "Sumter, Lake and Marion counties " + DEEP + " The Villages&rsquo; lineup shifts every October."), ("Will my Villages doctors take a Medicare Advantage plan?", NET), ("How much does your help cost?", COST)],
         ["ocala", "orlando"]),
    city("ocala", "Ocala", "Marion County", "central-florida", "liveoaks",
         "Ocala and Marion County are horse country turned retirement country, with AdventHealth Ocala and HCA Ocala in different networks and a growing menu.",
         ["Marion County offers a moderate-to-deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. AdventHealth Ocala and HCA Florida Ocala contract with different carriers; Gainesville&rsquo;s UF Health is forty minutes north for specialty care.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["AdventHealth Ocala", "HCA Florida Ocala", "UF Health Shands (Gainesville)", "Ocala VA Clinic"],
         "Ocala, Silver Springs, Belleview, Dunnellon, On Top of the World, Marion Oaks, Summerfield",
         std("Ocala", "Marion County " + MOD), ["the-villages", "gainesville"]),
    city("tallahassee", "Tallahassee", "Leon County", "panhandle", "liveoaks",
         "Tallahassee has TMH and HCA Capital Regional in different networks, a moderate menu, and a large state-retiree population with its own coverage rules.",
         ["Leon County offers a moderate Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Tallahassee Memorial HealthCare and HCA Florida Capital contract with different carriers, and many Tallahassee retirees have state retiree coverage that changes the Part B and Part D calculation.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Tallahassee Memorial HealthCare", "HCA Florida Capital Hospital", "Tallahassee VA Clinic"],
         "Tallahassee, Killearn, SouthWood, Crawfordville, Quincy, Havana, Monticello",
         std("Tallahassee", "Leon County " + MOD), ["pensacola", "gainesville"]),
    city("pensacola", "Pensacola", "Escambia County", "panhandle", "beach",
         "Pensacola is a Navy town with Baptist and Ascension Sacred Heart in different networks, a moderate menu, and doctors in Mobile that a Medigap policy covers automatically.",
         ["Escambia and Santa Rosa counties offer a moderate Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Baptist Health Care and Ascension Sacred Heart contract with different carriers, and NAS Pensacola and Whiting Field retirees carry TRICARE For Life, which changes the calculation; see our Pensacola and Eglin page.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Baptist Health Care", "Ascension Sacred Heart Pensacola", "HCA Florida West", "Naval Hospital Pensacola (TRICARE)", "Pensacola VA Clinic"],
         "Pensacola, Gulf Breeze, Pace, Milton, Navarre, Cantonment, Perdido Key, Pensacola Beach",
         std("Pensacola", "Escambia County " + MOD), ["pensacola-eglin", "tallahassee"]),
    city("gainesville", "Gainesville", "Alachua County", "north-central-florida", "liveoaks",
         "Gainesville is UF Health Shands, the region&rsquo;s academic center, plus HCA North Florida and one of the largest VA systems in the country.",
         ["Alachua County offers a moderate Advantage menu, every Medigap carrier in Florida and the full Part D lineup. UF Health Shands accepts Original Medicare and contracts selectively with Advantage plans; HCA Florida North Florida sits in a different network; the Malcom Randall VA serves veterans from a wide region.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["UF Health Shands", "HCA Florida North Florida", "Malcom Randall VA Medical Center"],
         "Gainesville, Newberry, Alachua, High Springs, Archer, Hawthorne, Micanopy",
         [("Which Medicare plans are available in Gainesville?", "Alachua County " + MOD), ("Does UF Health Shands take Medicare Advantage?", "Shands accepts Original Medicare and any Medigap policy, and contracts with some Advantage plans and not others. We confirm before you enroll."), ("How much does your help cost?", COST)],
         ["ocala", "jacksonville"]),
    city("daytona-beach", "Daytona Beach", "Volusia County", "treasure-space-coast", "spacecoast",
         "Volusia County is split between Halifax Health and AdventHealth, with a deep menu and a coast full of retirees from Ormond to New Smyrna.",
         ["Volusia County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Halifax Health and AdventHealth Daytona Beach contract with different carriers, and which one your doctors belong to decides the shortlist.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Halifax Health", "AdventHealth Daytona Beach &amp; New Smyrna", "AdventHealth Fish Memorial (Orange City)", "Daytona Beach VA Clinic"],
         "Daytona Beach, Ormond Beach, Port Orange, New Smyrna Beach, DeLand, Deltona, Palm Coast, Flagler Beach",
         std("Daytona Beach", "Volusia County " + DEEP), ["melbourne", "orlando", "jacksonville"]),
    city("melbourne", "Melbourne", "Brevard County", "treasure-space-coast", "spacecoast",
         "Brevard is Health First country &mdash; the dominant system also sells its own Advantage plans &mdash; with Patrick Space Force Base and the Viera VA clinic alongside.",
         ["Brevard County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Health First runs the main hospitals and its own plans; Parrish Medical Center and Steward&rsquo;s former hospitals sit in other networks; Patrick Space Force Base retirees carry TRICARE For Life.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Health First (Holmes, Viera, Cape Canaveral, Palm Bay)", "Parrish Medical Center", "Rockledge Regional", "Viera VA Clinic"],
         "Melbourne, Palm Bay, Viera, Cocoa, Cocoa Beach, Titusville, Merritt Island, Satellite Beach, Indialantic",
         std("Melbourne", "Brevard County " + DEEP), ["port-st-lucie", "daytona-beach", "orlando"]),
    city("port-st-lucie", "Port St. Lucie", "St. Lucie County", "treasure-space-coast", "keys",
         "Port St. Lucie is one of the fastest-growing cities in America, with Cleveland Clinic Tradition and HCA St. Lucie in different networks and a lineup that changes every October.",
         ["St. Lucie and Martin counties offer a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Cleveland Clinic Tradition and Martin North, HCA Florida St. Lucie and Lawnwood contract with different carriers, and most residents arrived recently from elsewhere.",
          "We compare what is sold at your ZIP code and, for new residents, check what the move did to your plan and Medigap rights."],
         ["Cleveland Clinic Tradition Hospital", "HCA Florida St. Lucie &amp; Lawnwood", "Cleveland Clinic Martin North (Stuart)", "Port St. Lucie VA Clinic"],
         "Port St. Lucie, Tradition, Fort Pierce, Stuart, Jensen Beach, Palm City, Vero Beach",
         std("Port St. Lucie", "St. Lucie County " + DEEP), ["west-palm-beach", "melbourne"]),
    city("lakeland", "Lakeland", "Polk County", "central-florida", "citrus",
         "Polk County sits between Tampa and Orlando with Lakeland Regional, one of the busiest hospitals in the state, at its center and a deep menu that draws from both metros.",
         ["Polk County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. Lakeland Regional Health, AdventHealth Lake Wales and Heart of Florida, and BayCare Winter Haven contract with different carriers, and referrals to Tampa or Orlando are common.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Lakeland Regional Health", "BayCare Winter Haven", "AdventHealth Heart of Florida &amp; Lake Wales", "Lakeland VA Clinic"],
         "Lakeland, Winter Haven, Auburndale, Bartow, Haines City, Lake Wales, Davenport, Mulberry",
         std("Lakeland", "Polk County " + DEEP), ["tampa", "orlando"]),
    city("clearwater", "Clearwater", "Pinellas County", "tampa-bay", "beach",
         "Clearwater, Dunedin and Palm Harbor are BayCare&rsquo;s home turf &mdash; Morton Plant and Mease &mdash; with a deep menu that lost some UnitedHealthcare plans for 2026.",
         ["Pinellas County offers a deep Advantage menu, every Medigap carrier in Florida and the full Part D lineup. BayCare Morton Plant and Mease contract selectively, HCA Florida Largo and Trinity sit in other networks, and Bay Pines VA is a short drive south.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["BayCare Morton Plant &amp; Mease", "HCA Florida Largo &amp; Trinity", "Bay Pines VA Healthcare System"],
         "Clearwater, Dunedin, Palm Harbor, Safety Harbor, Largo, Oldsmar, Tarpon Springs, Belleair",
         [("Which Medicare plans are available in Clearwater?", "Pinellas County " + DEEP + " For 2026 UnitedHealthcare reduced its plans here."), ("Is Morton Plant in my plan&rsquo;s network?", NET), ("How much does your help cost?", COST)],
         ["st-petersburg", "tampa"]),
]

BASES = [
    dict(slug="jacksonville-navy", name="NAS Jacksonville &amp; Mayport", region="northeast-florida", scene="lighthouse",
         title="Medicare Near NAS Jacksonville &amp; Mayport, FL | ECOS Medicare Solutions",
         desc="Medicare for Navy retirees and veterans around NAS Jacksonville, Naval Station Mayport and Orange Park: TRICARE For Life, Naval Hospital Jacksonville, the Jacksonville VA, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near NAS Jacksonville and Naval Station Mayport",
         sub="Northeast Florida retires more sailors than almost anywhere. TRICARE For Life, Naval Hospital Jacksonville, the Jacksonville VA clinics &mdash; and a Medicare decision that looks different from a civilian one, explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Navy family on the First Coast",
         intro=["Duval and Clay counties hold tens of thousands of Navy retirees, and most reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having, and whether its network includes Baptist, Mayo or St. Vincent&rsquo;s.",
                "Veterans without TRICARE use the Jacksonville VA clinics and the Gainesville and Lake City medical centers, and here the Part B timing question is the one that matters: VA care is not creditable for Part B, so delaying Part B because you have the VA triggers a lifelong penalty. Naval Hospital Jacksonville sees retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["Naval Hospital Jacksonville (TRICARE)", "Jacksonville VA clinics; Malcom Randall VA (Gainesville)", "Baptist Health Jacksonville", "Mayo Clinic Jacksonville", "Ascension St. Vincent&rsquo;s", "HCA Florida Orange Park"],
         communities="Orange Park, Fleming Island, Middleburg, Mandarin, Westside, Atlantic Beach, Neptune Beach, Jacksonville Beach, Mayport, Arlington",
         faqs=[("I retired from the Navy with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one is worth it for you."),
               ("I use the Jacksonville VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at a non-VA hospital. Enroll on time."),
               ("Can I keep using Naval Hospital Jacksonville after 65?", "Retirees can be seen on a space-available basis under TRICARE rules; Medicare does not pay there. Most Jacksonville Navy retirees pair TFL with civilian care at Baptist, Mayo or St. Vincent&rsquo;s.")],
         nearby=["jacksonville", "gainesville", "daytona-beach"], cta="Retired from the Navy? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="macdill-afb", name="MacDill Air Force Base", region="tampa-bay", scene="macdill",
         title="Medicare Near MacDill Air Force Base, Tampa | ECOS Medicare Solutions",
         desc="Medicare for Air Force retirees and veterans around MacDill AFB and South Tampa: TRICARE For Life, the 6th Medical Group, the Haley and Bay Pines VA, and which Tampa Bay plans fit. From a retired Air Force officer.",
         h1="Medicare near MacDill Air Force Base",
         sub="Tampa Bay has one of the largest Air Force retiree communities in the country. TRICARE For Life, the 6th Medical Group clinic, the Haley and Bay Pines VA &mdash; and a Medicare decision that looks different from a civilian one, explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a MacDill family",
         intro=["Hillsborough and Pinellas hold tens of thousands of Air Force retirees, and most reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having, and whether its network includes Tampa General, BayCare or Moffitt.",
                "Veterans without TRICARE use the James A. Haley VA in Tampa or Bay Pines in St. Petersburg, two of the busiest VA centers anywhere, and here the Part B timing question is the one that matters. The 6th Medical Group on base sees retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["MacDill 6th Medical Group (TRICARE)", "James A. Haley VA (Tampa)", "Bay Pines VA (St. Petersburg)", "Tampa General Hospital", "BayCare St. Joseph&rsquo;s", "Moffitt Cancer Center"],
         communities="South Tampa, Bayshore, Westshore, Gandy, Brandon, Riverview, Apollo Beach, St. Petersburg, Pinellas Park",
         faqs=[("I retired from the Air Force with TRICARE For Life. Which Medicare plan should I pick?", "For most TFL families, Original Medicare Parts A and B with TFL is complete coverage. An MA-only Advantage plan can add dental, vision and hearing without duplicating your pharmacy benefit; we check whether one is worth it for you."),
               ("Does Medicare pay at the MacDill clinic?", "No. The 6th Medical Group sees retirees on a space-available basis under TRICARE rules. Most MacDill retirees pair TFL with civilian care at Tampa General, BayCare or HCA."),
               ("I use the Haley VA and do not have TRICARE. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty and leaves you uncovered at a non-VA hospital.")],
         nearby=["tampa", "st-petersburg", "clearwater"], cta="Retired from MacDill? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="pensacola-eglin", name="Pensacola &amp; Eglin military communities", region="panhandle", scene="beach",
         title="Medicare Near NAS Pensacola, Eglin &amp; Hurlburt, FL | ECOS Medicare Solutions",
         desc="Medicare for military retirees around NAS Pensacola, Whiting Field, Eglin AFB, Hurlburt Field and Tyndall: TRICARE For Life, the military hospitals, the Pensacola VA, and which Panhandle plans fit. From a retired Air Force officer.",
         h1="Medicare near NAS Pensacola, Eglin and Hurlburt",
         sub="The Emerald Coast has more military retirees per capita than almost anywhere in America. TRICARE For Life, Naval Hospital Pensacola, the Eglin hospital, the Pensacola VA &mdash; and a Medicare decision that looks different from a civilian one.",
         h2="Why the Medicare choice is different on the Emerald Coast",
         intro=["Escambia, Santa Rosa, Okaloosa and Bay counties hold one of the densest military-retiree populations in the country, from NAS Pensacola and Whiting Field to Eglin, Hurlburt and Tyndall. Most reach 65 with TRICARE For Life, which requires Medicare Parts A and B, pays secondary to Medicare and carries creditable pharmacy coverage. A Medigap policy and a Part D plan are usually redundant for a TFL family; the open question is whether an MA-only Advantage plan&rsquo;s extras are worth it, and whether its network includes Baptist, Sacred Heart or the HCA hospitals.",
                "Naval Hospital Pensacola and the Eglin hospital see retirees on a space-available basis; Medicare does not pay there. The Pensacola VA clinic and the Biloxi VA serve veterans without TFL, for whom the Part B timing rule is the one that matters."],
         systems=["Naval Hospital Pensacola (TRICARE)", "Eglin AFB Hospital (TRICARE)", "Pensacola VA Clinic; Biloxi VA", "Baptist Health Care", "Ascension Sacred Heart (Pensacola, Destin)", "HCA Florida West &amp; Fort Walton-Destin"],
         communities="Pensacola, Gulf Breeze, Navarre, Milton, Pace, Fort Walton Beach, Destin, Niceville, Crestview, Mary Esther, Panama City",
         faqs=[("I retired from the Navy or Air Force with TRICARE For Life. Do I need anything besides Medicare A and B?", "Usually not. TFL fills Medicare&rsquo;s gaps and its pharmacy is creditable. An MA-only Advantage plan can add dental or vision; we check whether one is worth it and whether its network reaches your doctors."),
               ("Does Medicare pay at Naval Hospital Pensacola or the Eglin hospital?", "No. Both see retirees on a space-available basis under TRICARE rules. Most Emerald Coast retirees pair TFL with civilian care at Baptist, Sacred Heart or HCA."),
               ("I use the Pensacola VA. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty.")],
         nearby=["pensacola", "tallahassee"], cta="Retired on the Emerald Coast? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
]
