"""Florida topic pages, part A: Advantage, Medigap, Part D."""
SRC_CMS = ("CMS: 2026 Medicare Parts A &amp; B Premiums and Deductibles (Nov 14, 2025)", "https://www.cms.gov/newsroom/fact-sheets/2026-medicare-parts-b-premiums-and-deductibles")
SRC_COSTS = ("Medicare.gov: Medicare costs", "https://www.medicare.gov/basics/costs/medicare-costs")
SRC_MA_GOV = ("Medicare.gov: Medicare Advantage plans", "https://www.medicare.gov/health-drug-plans/health-plans")
SRC_MEDIGAP_GOV = ("Medicare.gov: Medigap (Medicare Supplement Insurance)", "https://www.medicare.gov/health-drug-plans/medigap")
SRC_PARTD_GOV = ("Medicare.gov: Drug coverage (Part D)", "https://www.medicare.gov/health-drug-plans/part-d")
SRC_SHINE = ("Florida Department of Elder Affairs: SHINE (1-800-963-5337)", "https://elderaffairs.org/programs-and-services/serving-health-insurance-needs-of-elders-shine/")
SRC_FLOIR = ("Florida Office of Insurance Regulation: Medicare supplement (Medigap) consumer information", "https://www.floir.com/consumers/health-insurance")
SRC_KFF_MEDIGAP = ("KFF: Key facts about Medigap enrollment and premiums (rating rules by state)", "https://www.kff.org/medicare/key-facts-about-medigap-enrollment-and-premiums-for-medicare-beneficiaries/")
SRC_MRO = ("medicareresources.org: Medigap eligibility for people under 65, by state", "https://www.medicareresources.org/medicare-eligibility-and-enrollment/medigap-eligibility-for-americans-under-age-65-varies-by-state/")
SRC_KFF = ("KFF: Medicare Advantage 2026 Spotlight, a first look at plan offerings", "https://www.kff.org/medicare/medicare-advantage-2026-spotlight-a-first-look-at-plan-offerings/")
SRC_HCD = ("Healthcare Dive: UnitedHealthcare, Humana, Aetna scale back Medicare Advantage plans for 2026", "https://www.healthcaredive.com/news/medicare-advantage-plans-2026-unitedhealthcare-humana-aetna/801761/")
SRC_MMR_FL = ("MyMedigapRate: Florida Medigap rate history, filing by filing", "https://www.mymedigaprate.com/medigap-rate-history/florida")
SRC_ACCESS = ("ACCESS Florida (Department of Children and Families): apply for Medicaid and Medicare Savings Programs", "https://www.myflfamilies.com/services/public-assistance")
SRC_AHCA = ("Florida Agency for Health Care Administration: Statewide Medicaid Managed Care", "https://ahca.myflorida.com/medicaid/statewide-medicaid-managed-care")
SRC_ELDER_HELP = ("Florida Department of Elder Affairs: help with health expenses", "https://elderaffairs.org/programs-and-services/health-expenses-help/")
SRC_CMS_HURR = ("CMS: hurricane and tropical storm emergency response actions", "https://www.cms.gov/about-cms/what-we-do/emergency-response/past-emergencies/hurricanes-tropical-storms")
SRC_SEP = ("Medicare.gov: Special Enrollment Periods, including FEMA-declared disasters", "https://www.medicare.gov/basics/get-started-with-medicare/get-more-coverage/joining-a-plan/special-enrollment-periods")
SRC_TFL = ("TRICARE For Life", "https://www.tricare.mil/tfl")
SRC_VA = ("VA health care and other insurance", "https://www.va.gov/health-care/about-va-health-benefits/va-health-care-and-other-insurance/")

TOPICS_A = [
dict(slug="medicare-advantage", nav_title="Medicare Advantage plans in Florida", crumb="Medicare Advantage", scene="miami",
     title="Medicare Advantage Plans in Florida [[YEAR]] | ECOS Medicare Solutions",
     desc="Medicare Advantage in Florida: the carriers, why the 2026 changes (AvMed's exit, UnitedHealthcare's county cuts, trimmed extras) hit Florida hard, $0 premiums, and what a discontinued plan gives you. Free help from a licensed Florida agent.",
     llm="Medicare Advantage (Part C) in Florida: the carriers, the 2026 AvMed exit and UnitedHealthcare county reductions, networks built on hospital systems, what a non-renewal notice gives you",
     eyebrow="Plans · Part C", h1="Medicare Advantage plans in Florida",
     sub="All-in-one plans, often with a $0 premium and extras like dental and vision &mdash; the way most Floridians get their Medicare, and the part of the market that moved most for 2026.",
     keyfacts=["A Medicare Advantage plan bundles Part A, Part B and usually Part D into one private plan with a county-based network. You keep paying the Part B premium ([[YEAR]]: $202.90) plus any plan premium.",
               "More than half of Florida&rsquo;s Medicare beneficiaries are in Advantage plans, the highest share of any large state. Florida Blue sells in every county; Humana, CarePlus, Aetna, HealthSpring, UnitedHealthcare, Wellcare, Devoted, Simply, Freedom, Optimum, HealthSun and Molina cover most of the peninsula.",
               "For 2026 AvMed left the Florida Medicare market (about 35,000 members), UnitedHealthcare reduced plans in Miami-Dade, Broward, Palm Beach, Hillsborough, Pinellas, Lee, Collier and other counties, and several carriers trimmed dental, vision and OTC extras.",
               "A discontinued plan gives you a Special Enrollment Period and, in most cases, a guaranteed-issue right to buy a Medigap policy without health questions, generally within 63 days of the coverage ending."],
     body="""<p>A Medicare Advantage plan (also called Part C) is an all-in-one alternative to Original Medicare, offered by private insurers that Medicare approves and pays. You still have Medicare, but the plan administers your Part A and Part B coverage and almost always folds in Part D drug coverage too. Florida is the most Advantage-heavy large state in the country, and its menu is correspondingly deep &mdash; which is exactly why the 2026 changes landed so hard here.</p>
<h2>What&rsquo;s usually included</h2>
<ul>
<li><strong>Hospital and medical coverage</strong> (your Part A and Part B benefits).</li>
<li><strong>Prescription drug coverage</strong> in most plans &mdash; so you don&rsquo;t buy a separate <a href="/part-d">Part D plan</a>.</li>
<li><strong>Extras Original Medicare doesn&rsquo;t cover</strong>, which can include dental, vision, hearing, fitness benefits, an over-the-counter allowance, and an annual out-of-pocket maximum that caps what you spend on covered care. Several Florida carriers trimmed those extras for 2026.</li>
</ul>
<h2>The trade-off: networks, county by county</h2>
<p>Advantage plans use provider networks (HMO or PPO) and are sold by county. That is the single most important thing to check before you enroll: whether your doctors and your hospital are in the plan&rsquo;s network, and whether your medications are on its drug list. Florida&rsquo;s systems &mdash; Baptist Health South Florida, Jackson, UHealth, Memorial, Cleveland Clinic Florida, Tampa General, BayCare, AdventHealth, Orlando Health, Lee Health, Mayo Jacksonville, Sarasota Memorial &mdash; each contract with some plans and not others, and the academic centers (Mayo, Moffitt, UHealth, UF Health) contract selectively. We confirm your providers and prescriptions are covered before you sign anything.</p>
<div class="warn-box"><p><strong>What changed for 2026, and why it matters this fall.</strong> AvMed, a Florida carrier since the 1960s, left the Medicare market entirely. UnitedHealthcare reduced or withdrew plans across South Florida, Tampa Bay and the Gulf Coast. Nationally, the large carriers exited hundreds of counties and raised premiums on plans that charge one, and extras were cut almost everywhere. If you were moved into a new plan, or picked one in a hurry last fall, the Annual Election Period starting October 15 is the time to check it actually fits &mdash; and to check whether your doctor is still in it, because Florida also saw a wave of mid-year provider terminations.</p></div>
<h2>If your plan was discontinued, or dropped your doctor</h2>
<p>A non-renewal notice is not just bad news; it opens doors. You get a Special Enrollment Period that runs past the normal deadlines, and because the plan left you involuntarily, federal rules give most people a <strong>guaranteed-issue right</strong> to buy a <a href="/medicare-supplement">Medigap policy</a> without medical underwriting &mdash; even if you are well past your original six-month Medigap window. The right is time-limited (generally 63 days after your coverage ends), so do not let the notice sit. A doctor dropped mid-year is a harder case: it does not by itself open a Special Enrollment Period, though a significant network change sometimes does. Call us and we will check.</p>
<h2>Who Medicare Advantage tends to suit</h2>
<p>People who want predictable, lower upfront costs and value bundled extras, who are comfortable using a plan network, and who stay in Florida most of the year. If you split the year with the Northeast or Midwest, see specialists outside the network, or want to use any provider nationwide, compare it against a <a href="/medicare-supplement">Medigap policy</a> &mdash; our <a href="/new-to-florida">new-to-Florida and snowbird guide</a> walks through the difference. Military retirees with TRICARE For Life have their own calculation; see <a href="/veterans">Veterans</a>.</p>
<p>There are also specialized Advantage plans for specific situations: <a href="/chronic-snp">Chronic Special Needs Plans (C-SNPs)</a>, <a href="/institutional-snp">Institutional SNPs (I-SNPs)</a>, and Dual Special Needs Plans for people with both Medicare and <a href="/medicaid">Florida Medicaid</a>, which are a large part of the menu in South Florida and Central Florida.</p>""",
     faqs=[("Does Medicare Advantage replace Original Medicare?", "Not exactly. You keep Medicare, but a private Advantage plan administers your benefits and adds extras. You generally use the plan&rsquo;s network and its rules instead of Original Medicare&rsquo;s."),
           ("Is there really a $0 premium?", "Many Advantage plans have a $0 monthly plan premium, but you still pay your Part B premium ($202.90 in [[YEAR]]), and you may have copays, coinsurance and a deductible. We show you the full picture, not just the premium."),
           ("My Florida Advantage plan was discontinued. Can I get a Medigap policy now?", "In most cases, yes. Losing your plan through no fault of your own gives you a guaranteed-issue right to buy a Medigap policy without health questions, generally within 63 days of the coverage ending, plus a Special Enrollment Period to pick a new Advantage or Part D plan. Call before the deadline on your notice."),
           ("Can I switch later if it isn&rsquo;t a fit?", "Yes. You can change during the Annual Election Period (Oct 15&ndash;Dec 7), and the Medicare Advantage Open Enrollment Period (Jan 1&ndash;Mar 31) lets current Advantage members switch once or return to Original Medicare. Moving counties, a FEMA disaster declaration and other circumstances open other windows.")],
     sources=[SRC_MA_GOV, SRC_KFF, SRC_HCD, SRC_SHINE, SRC_CMS], cta="Let&rsquo;s compare your Advantage options &mdash; and the alternatives.", about="Medicare Advantage in Florida"),

dict(slug="medicare-supplement", nav_title="Medicare Supplement (Medigap) plans in Florida", crumb="Medicare Supplement", scene="lighthouse",
     title="Medicare Supplement Plans in Florida: Issue-Age Rating &amp; the Rules | ECOS Medicare Solutions",
     desc="Florida Medigap explained: the standardized plans, why Florida requires issue-age rating and what it does to prices, the six-month open enrollment, the under-65 guaranteed-issue window, and comparing carriers on filed rate history.",
     llm="Medicare Supplement (Medigap) in Florida: standardized plans A-N, issue-age rating (attained-age prohibited), the six-month open enrollment, the under-65 guaranteed-issue window, no birthday rule, comparing carriers on rate history",
     eyebrow="Plans · Medigap", h1="Medicare Supplement (Medigap) plans in Florida",
     sub="A Medigap policy works alongside Original Medicare to pay much of what it leaves to you, and lets you use any provider in the country that accepts Medicare &mdash; Mayo, Moffitt, Cleveland Clinic, or your doctor back in Ohio. In Florida, the age you buy it decides the price for life.",
     keyfacts=["Florida uses the federal standardized plans, sold by letter (Plan G and Plan N are the most common for people new to Medicare; Plan F is closed to anyone eligible after 2019). The same letter offers the same benefits from every company.",
               "Florida requires <strong>issue-age rating</strong> and prohibits attained-age rating: your premium is set by your age when you buy and cannot rise because you got older, only with the carrier&rsquo;s filed increases. That rewards buying at 65 and holding on.",
               "Your six-month Medigap open enrollment starts the month you are 65 or older and enrolled in Part B. Florida also gives people under 65 on Medicare a six-month guaranteed-issue window when they enroll in Part B, and insurers must offer them at least one plan. There is no birthday rule.",
               "Losing an Advantage plan or employer coverage through no fault of your own creates a guaranteed-issue right, generally 63 days long. Florida&rsquo;s premiums run above most states&rsquo;; the filed rate history tells you which carriers hold steady."],
     body="""<p>Medicare Supplement insurance &mdash; usually called Medigap &mdash; is private coverage that pairs with Original Medicare (Parts A and B). Instead of replacing Medicare, it fills the gaps: the deductibles, copayments and coinsurance you&rsquo;d otherwise pay yourself. You then add a standalone <a href="/part-d">Part D drug plan</a> for prescriptions. The Florida Office of Insurance Regulation regulates the policies; the benefits inside each plan letter are set federally; the pricing rules are Florida&rsquo;s own.</p>
<h2>How Medigap is different from Advantage</h2>
<table class="ctable">
<caption>A simplified comparison &mdash; the right choice depends on your health, doctors, county and budget.</caption>
<thead><tr><th scope="col">&nbsp;</th><th scope="col">Medicare Supplement (Medigap)</th><th scope="col">Medicare Advantage</th></tr></thead>
<tbody>
<tr><th scope="row">Provider access</th><td>Any provider in the U.S. that accepts Medicare &mdash; no networks, no county lines, no state lines</td><td>Plan network (HMO/PPO), sold by county</td></tr>
<tr><th scope="row">Drug coverage</th><td>Add a separate Part D plan</td><td>Usually built in</td></tr>
<tr><th scope="row">Monthly premium</th><td>A monthly premium, higher in Florida than most states</td><td>Often $0 plan premium</td></tr>
<tr><th scope="row">Out-of-pocket</th><td>Very predictable; little to pay at the point of care on Plan G</td><td>Copays/coinsurance up to an annual cap</td></tr>
<tr><th scope="row">Extras (dental/vision)</th><td>Not included</td><td>Often included, trimmed for 2026</td></tr>
<tr><th scope="row">Summers up north</th><td>Covered anywhere in the U.S.</td><td>Emergencies only on most plans out of area</td></tr>
</tbody></table>
<h2>Issue-age rating: the Florida rule that decides your price</h2>
<p>Most states let insurers use <em>attained-age</em> rating, where your premium climbs every year simply because you are a year older. Florida prohibits it. Every Florida Medigap policy is <strong>issue-age</strong> rated: the premium is set by the age at which you buy, and it can rise only through the carrier&rsquo;s filed, across-the-board increases &mdash; never because your birthday came around. Two consequences follow. A policy bought at 65 is priced at 65 forever, so buying early and holding on is rewarded. And because insurers price that promise in, and Florida&rsquo;s claims costs are high, Florida premiums run well above most states&rsquo; at the start. If you moved here with an attained-age policy from another state, ask us to compare; the math is not obvious.</p>
<h2>The plans Floridians actually buy</h2>
<p><strong>Plan G</strong> covers everything Original Medicare leaves behind except the Part B deductible ($283 in [[YEAR]]). <strong>Plan N</strong> costs less in exchange for small office and emergency copays and no coverage of Part B excess charges. <strong>High-deductible Plan G</strong> has a much lower premium and a deductible you pay first, and it is popular in Florida precisely because standard premiums are high. <strong>Plan F</strong> still exists for people who were eligible before 2020 but cannot be sold to anyone newer.</p>
<h2>When you can buy one without health questions</h2>
<ul>
<li><strong>Your six-month open enrollment.</strong> It starts the month you are 65 or older <em>and</em> enrolled in Part B. During it, every plan a company sells is guaranteed available regardless of health.</li>
<li><strong>Under 65 on disability or ESRD.</strong> Since 2009 Florida gives people under 65 their own six-month guaranteed-issue window when they enroll in Part B, and insurers must offer at least one plan. Premiums for under-65 buyers can differ from seniors&rsquo; but must be the same for everyone under 65. A fresh open enrollment for every plan arrives at 65.</li>
<li><strong>Guaranteed-issue events.</strong> Losing an Advantage plan or employer coverage through no fault of your own gives you a window (generally 63 days) to buy certain plans without underwriting. AvMed&rsquo;s exit and the 2026 county cuts triggered this for many Floridians.</li>
<li><strong>Outside those windows,</strong> Florida insurers can use medical underwriting, and Florida has no birthday rule, anniversary rule or annual Medigap window. Switching later usually means answering health questions.</li>
</ul>
<div class="note-box"><p><strong>Moving from a guaranteed-issue state?</strong> New York, Connecticut, Massachusetts and Maine let residents buy or switch Medigap year-round without underwriting. Florida does not. If you are moving here from one of them and are past 65, the move itself does not create a Florida guaranteed-issue right for Medigap; keeping your existing policy, or buying before you leave, may be the better move. Our <a href="/new-to-florida">new-to-Florida guide</a> covers it.</p></div>
<h2>Compare the rate history, not just the first-year price</h2>
<p>Because the benefits are standardized and the rating method is fixed by law, the only real differences between Florida Medigap companies are what they charge and how steeply they raise it later through filed increases. That second part is public: every carrier files its rate increases with the Office of Insurance Regulation, and a policy that looks cheap at 65 can be the expensive one by 75. We publish that filing history on our research site, <a href="https://www.mymedigaprate.com/medigap-rate-history/florida">Florida Medigap rate history</a>, with each figure tied to the filing it came from. If your premium has already gone up and you want to know why, <a href="https://www.mymedigaprate.com/why-did-my-medigap-premium-increase">why Medigap premiums increase</a> covers the three causes.</p>
<h2>Who Medigap tends to suit</h2>
<p>People who want maximum freedom to choose doctors and hospitals &mdash; Mayo, Moffitt, Cleveland Clinic and UHealth without a network question &mdash; predictable costs, and coverage that travels. That last point is why so many Florida snowbirds and part-year residents keep a supplement despite the premium. The cost is a monthly premium that, in Florida, rises only with the carrier&rsquo;s filings.</p>""",
     faqs=[("Do I need a separate drug plan with Medigap?", "Yes. Medigap does not include prescription coverage, so most people add a standalone Part D plan. We help you pick one around your specific medications."),
           ("What is issue-age rating and why does Florida require it?", "Under issue-age rating your premium is based on the age at which you buy the policy and cannot rise because you got older, only with the carrier&rsquo;s filed increases. Florida requires it and prohibits attained-age rating, which is why Florida premiums start higher than most states&rsquo; but do not climb with each birthday."),
           ("Can I be turned down for Medigap in Florida?", "Not during your six-month open enrollment, not during Florida&rsquo;s under-65 window, and not during a guaranteed-issue event such as your Advantage plan being discontinued. Outside those windows, Florida insurers can use medical underwriting, and Florida has no birthday rule."),
           ("Is Plan F still available in Florida?", "Only to people who became eligible for Medicare before January 1, 2020. Everyone newer chooses from Plans G, N, high-deductible G and the others. We walk through which fits you."),
           ("How much does a Florida Medigap policy cost?", "It depends on the plan letter, your age when you buy, ZIP code, tobacco use and the carrier, and every carrier raises rates on its own schedule through filed increases. Florida premiums run above most states&rsquo;. We compare current premiums and each company&rsquo;s filed rate history with you; we do not publish a number here without the filing behind it.")],
     sources=[SRC_MEDIGAP_GOV, SRC_KFF_MEDIGAP, SRC_MRO, SRC_FLOIR, SRC_MMR_FL, SRC_CMS], cta="Let&rsquo;s see whether Plan G, Plan N or something else fits you.", about="Medicare supplement insurance in Florida"),

dict(slug="part-d", nav_title="Medicare Part D plans in Florida", crumb="Part D", scene="citrus",
     title="Medicare Part D Plans in Florida [[YEAR]] | ECOS Medicare Solutions",
     desc="Part D drug plans in Florida: the [[YEAR]] $2,100 cap, $615 maximum deductible, choosing by your medications and pharmacy (Publix, CVS, Walgreens, Walmart), the late penalty, hurricane refills, and Extra Help.",
     llm="Part D drug plans in Florida: 2026 $2,100 cap, choosing by your medications and pharmacy, penalties, early refills in a hurricane emergency, Extra Help through Florida's Medicare Savings Programs",
     eyebrow="Plans · Part D", h1="Medicare Part D drug plans in Florida",
     sub="Standalone prescription coverage chosen around your medications and your pharmacy &mdash; whether you pair it with Original Medicare, a Medigap policy, or nothing else.",
     keyfacts=["[[YEAR]] Part D out-of-pocket cap: $2,100. Once your spending on covered drugs reaches it, you pay $0 for covered medications the rest of the year.",
               "[[YEAR]] maximum Part D deductible: $615; many plans set a lower one or none. The national base premium used for penalties is $38.99.",
               "Going 63 or more days without creditable drug coverage after you are first eligible adds a permanent penalty to your premium. TRICARE For Life and VA pharmacy are creditable.",
               "During a declared hurricane emergency, Part D plans must allow early refills and relax pharmacy restrictions in the affected area. Qualifying for a Florida Medicare Savings Program automatically qualifies you for Extra Help."],
     body="""<p>Medicare Part D covers prescription drugs through private plans approved by Medicare. You can get it as a standalone plan alongside Original Medicare (and usually a <a href="/medicare-supplement">Medigap policy</a>), or built into most <a href="/medicare-advantage">Medicare Advantage</a> plans.</p>
<h2>What changed for [[YEAR]]</h2>
<ul>
<li><strong>$2,100 out-of-pocket cap.</strong> Once your spending on covered drugs reaches $2,100 in [[YEAR]], you pay $0 for covered medications the rest of the year.</li>
<li><strong>Deductible up to $615.</strong> That is the most a plan can charge as its [[YEAR]] deductible; many plans set a lower one or none at all.</li>
<li><strong>Premiums vary by plan.</strong> The [[YEAR]] national base beneficiary premium &mdash; the figure used to calculate penalties &mdash; is $38.99, but what you actually pay depends on the plan you choose.</li>
<li><strong>The Medicare Prescription Payment Plan</strong> lets you spread out-of-pocket drug costs across the year in monthly instalments instead of paying at the counter. It changes when you pay, not how much.</li>
</ul>
<h2>Choosing a plan is about your drug list and your pharmacy</h2>
<p>Every Part D plan has a formulary &mdash; its list of covered drugs and the tier (and cost) for each &mdash; and a pharmacy network with preferred pharmacies that cost less. Two plans with similar premiums can cost very different amounts once your specific prescriptions are run through them, and a plan that is cheap at Publix in Naples may be expensive at the independent pharmacy in Apalachicola. We compare plans using your actual medication list and your pharmacy, so the lowest <em>total</em> cost wins, not just the lowest premium.</p>
<div class="note-box"><p><strong>Watch the late-enrollment penalty.</strong> If you go 63 or more days without Part D or other creditable drug coverage after you are first eligible, a permanent penalty can be added to your premium for as long as you have Part D. Employer coverage, the VA pharmacy and TRICARE For Life are all creditable; keep proof. See our <a href="/medicare-costs">[[YEAR]] costs page</a> to estimate a penalty.</p></div>
<h2>Hurricanes and refills</h2>
<p>When a hurricane emergency is declared, Medicare requires Part D plans in the affected area to lift refill-too-soon limits so you can fill early before you evacuate, to allow out-of-network pharmacies when yours is closed, and to relax prior-authorization rules for medications you already take. Ask your pharmacy for an emergency refill as soon as a watch is posted; do not wait for the warning. Our <a href="/hurricanes">hurricanes page</a> covers the rest, including the enrollment deadline extension.</p>
<h2>Higher earners and lower incomes</h2>
<p>If your income is above the [[YEAR]] thresholds ($109,000 single / $218,000 joint, based on your 2024 tax return), you pay a Part D income-related surcharge (IRMAA) on top of your plan premium; our <a href="/medicare-costs">costs &amp; IRMAA page</a> lays out the brackets. At the other end, <strong>Extra Help</strong> (the Low-Income Subsidy) cuts Part D premiums and copays substantially for people with limited income and resources. In Florida, qualifying for a Medicare Savings Program (QMB, SLMB or QI) through the Department of Children and Families qualifies you for Extra Help automatically. See <a href="/medicaid">Florida Medicaid and the Medicare Savings Programs</a>.</p>""",
     faqs=[("When should I enroll in Part D?", "Usually when you first become eligible for Medicare, even if you take few or no medications &mdash; that avoids the late-enrollment penalty. Exceptions apply if you have other creditable drug coverage such as an employer plan, TRICARE For Life or VA pharmacy benefits."),
           ("What is the [[YEAR]] Part D out-of-pocket cap?", "$2,100. After your covered-drug spending reaches that amount in [[YEAR]], you pay nothing more for covered medications for the rest of the year."),
           ("Can I get an early refill before a hurricane?", "Yes, once an emergency is declared for your area. Part D plans must lift refill-too-soon limits and allow out-of-network pharmacies in the affected area. Ask your pharmacy as soon as a watch is posted."),
           ("Can you help me pick a plan around my medications?", "Yes &mdash; that is the most useful thing we do here. Bring your medication list and pharmacy, and we compare plans on your total expected yearly cost.")],
     sources=[SRC_PARTD_GOV, SRC_CMS, SRC_COSTS, SRC_CMS_HURR, SRC_ACCESS], cta="Let&rsquo;s match a drug plan to your prescriptions.", about="Medicare Part D in Florida"),
]
